name: Copilot Usage
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  run:
    name: Run Action
    runs-on: ubuntu-latest
    steps:
      - uses: austenstone/copilot-usage@v5.2
        with:
          github-token: ${{ secrets.PAT }}
          time-zone: 'JST'
      - uses: austenstone/job-summary@v2.0
        with:
          name: copilot-usage
